apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: backend-order
          image: harsh3305/hrv-mart-backend-order
          ports:
            - containerPort: 8085
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: mongodb-uri
                  name: config-map
            - name: KAFKA_URL
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: kafka-url
---
apiVersion: v1
kind: Service
metadata:
  name: backend-order-service
spec:
  selector:
    app: order
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30005